# Numpy and Basic of Graph

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
l1= [4,5,6,7,"python",34,565,True]

In [5]:
a1 = np.array(l1)

In [6]:
a1

array(['4', '5', '6', '7', 'python', '34', '565', 'True'], dtype='<U11')

In [7]:
a2 = np.array([[1,2,3], [4,5,6]])

In [8]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]]])

In [10]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
a1.ndim

1

In [12]:
a2.ndim

2

In [13]:
a3.ndim

3

In [14]:
a1.size

8

In [15]:
a2.size

6

In [16]:
a3.size

9

In [17]:
a1.shape

(8,)

In [18]:
a2.shape

(2, 3)

In [19]:
a3.shape

(1, 3, 3)

In [20]:
np.random.randint(2,50,(3,4))

array([[43, 25, 46,  5],
       [38, 34, 16, 48],
       [24, 27, 35, 33]])

In [21]:
np.random.randint(2,50,(2,3,4))

array([[[41, 40, 27, 27],
        [15, 21, 27, 42],
        [21, 18, 40, 14]],

       [[43, 38, 16, 44],
        [22, 21,  5, 13],
        [37, 43, 34, 39]]])

In [22]:
np.random.rand(5,4)

array([[0.23158579, 0.77422619, 0.50494292, 0.54622802],
       [0.73236741, 0.4339853 , 0.52271384, 0.82663114],
       [0.58943353, 0.25052608, 0.24380165, 0.67920874],
       [0.67327199, 0.54765214, 0.19843325, 0.06257514],
       [0.22520651, 0.97531733, 0.42961081, 0.80238725]])

In [23]:
a4 = np.random.randn(4,4)

In [24]:
a4

array([[-0.62451964,  0.38624685,  0.25789902,  0.32779511],
       [ 1.07219242,  0.41878358,  0.27582083, -0.76226173],
       [ 1.99661659,  0.66677575,  1.46873483,  0.04805775],
       [ 1.51076832, -0.73832866, -0.71160851,  0.34361173]])

In [25]:
a4.reshape(2,8)

array([[-0.62451964,  0.38624685,  0.25789902,  0.32779511,  1.07219242,
         0.41878358,  0.27582083, -0.76226173],
       [ 1.99661659,  0.66677575,  1.46873483,  0.04805775,  1.51076832,
        -0.73832866, -0.71160851,  0.34361173]])

In [26]:
a4.reshape(8,2)

array([[-0.62451964,  0.38624685],
       [ 0.25789902,  0.32779511],
       [ 1.07219242,  0.41878358],
       [ 0.27582083, -0.76226173],
       [ 1.99661659,  0.66677575],
       [ 1.46873483,  0.04805775],
       [ 1.51076832, -0.73832866],
       [-0.71160851,  0.34361173]])

In [27]:
a4.reshape(16,1)

array([[-0.62451964],
       [ 0.38624685],
       [ 0.25789902],
       [ 0.32779511],
       [ 1.07219242],
       [ 0.41878358],
       [ 0.27582083],
       [-0.76226173],
       [ 1.99661659],
       [ 0.66677575],
       [ 1.46873483],
       [ 0.04805775],
       [ 1.51076832],
       [-0.73832866],
       [-0.71160851],
       [ 0.34361173]])

In [28]:
a4.reshape(2,-134564364)

array([[-0.62451964,  0.38624685,  0.25789902,  0.32779511,  1.07219242,
         0.41878358,  0.27582083, -0.76226173],
       [ 1.99661659,  0.66677575,  1.46873483,  0.04805775,  1.51076832,
        -0.73832866, -0.71160851,  0.34361173]])

In [29]:
a4.reshape(1,1,1,1,1,1,1,2,2,4)

array([[[[[[[[[[-0.62451964,  0.38624685,  0.25789902,
                 0.32779511],
               [ 1.07219242,  0.41878358,  0.27582083,
                -0.76226173]],

              [[ 1.99661659,  0.66677575,  1.46873483,
                 0.04805775],
               [ 1.51076832, -0.73832866, -0.71160851,
                 0.34361173]]]]]]]]]])

In [30]:
a1

array(['4', '5', '6', '7', 'python', '34', '565', 'True'], dtype='<U11')

In [31]:
a1[0]

'4'

In [32]:
a1[2:6]

array(['6', '7', 'python', '34'], dtype='<U11')

In [33]:
a1[2:6:2]

array(['6', 'python'], dtype='<U11')

In [34]:
a1[::-1]

array(['True', '565', '34', 'python', '7', '6', '5', '4'], dtype='<U11')

In [35]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [36]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [38]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [39]:
a2[[0,1], 1:]

array([[2, 3],
       [5, 6]])

In [40]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [41]:
a5 = np.random.randint(2,90, (6,5))

In [42]:
a5

array([[20, 29, 34, 18,  3],
       [79, 15, 73, 19, 43],
       [51, 65, 41, 48, 69],
       [78, 63, 26, 84, 21],
       [75, 54, 26, 75, 74],
       [82,  5, 22, 43, 18]])

In [43]:
a5[a5>40]

array([79, 73, 43, 51, 65, 41, 48, 69, 78, 63, 84, 75, 54, 75, 74, 82, 43])

In [44]:
a5[0,1] = 100

In [46]:
a5

array([[ 20, 100,  34,  18,   3],
       [ 79,  15,  73,  19,  43],
       [ 51,  65,  41,  48,  69],
       [ 78,  63,  26,  84,  21],
       [ 75,  54,  26,  75,  74],
       [ 82,   5,  22,  43,  18]])

In [47]:
a6 = np.random.randint(0,3, (3,3))

In [48]:
a7 = np.random.randint(0,3, (3,3))

In [49]:
a6

array([[1, 2, 1],
       [1, 1, 2],
       [1, 0, 0]])

In [50]:
a7

array([[1, 2, 1],
       [2, 0, 1],
       [1, 1, 2]])

In [51]:
a6*a7

array([[1, 4, 1],
       [2, 0, 2],
       [1, 0, 0]])

In [54]:
a6@a7

array([[6, 3, 5],
       [5, 4, 6],
       [1, 2, 1]])

In [55]:
a6

array([[1, 2, 1],
       [1, 1, 2],
       [1, 0, 0]])

In [56]:
a6+100

array([[101, 102, 101],
       [101, 101, 102],
       [101, 100, 100]])

In [57]:
a6*2

array([[2, 4, 2],
       [2, 2, 4],
       [2, 0, 0]])

In [58]:
a6/0

C:\Users\farid\AppData\Local\Temp\ipykernel_4492\1058679823.py:1: RuntimeWarning: divide by zero encountered in divide
  a6/0
C:\Users\farid\AppData\Local\Temp\ipykernel_4492\1058679823.py:1: RuntimeWarning: invalid value encountered in divide
  a6/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, nan, nan]])

In [59]:
a6

array([[1, 2, 1],
       [1, 1, 2],
       [1, 0, 0]])

In [60]:
a6**3

array([[1, 8, 1],
       [1, 1, 8],
       [1, 0, 0]], dtype=int32)

In [61]:
a8 = np.zeros((4,4))

In [62]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
a9 = np.ones((4,5))

In [69]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [70]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [71]:
a9 + np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [72]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [73]:
np.array([[1,2,3,4]]).T + a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [74]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [75]:
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [78]:
a5

array([[ 20, 100,  34,  18,   3],
       [ 79,  15,  73,  19,  43],
       [ 51,  65,  41,  48,  69],
       [ 78,  63,  26,  84,  21],
       [ 75,  54,  26,  75,  74],
       [ 82,   5,  22,  43,  18]])

In [76]:
np.sqrt(a5)

array([[ 4.47213595, 10.        ,  5.83095189,  4.24264069,  1.73205081],
       [ 8.88819442,  3.87298335,  8.54400375,  4.35889894,  6.55743852],
       [ 7.14142843,  8.06225775,  6.40312424,  6.92820323,  8.30662386],
       [ 8.83176087,  7.93725393,  5.09901951,  9.16515139,  4.58257569],
       [ 8.66025404,  7.34846923,  5.09901951,  8.66025404,  8.60232527],
       [ 9.05538514,  2.23606798,  4.69041576,  6.55743852,  4.24264069]])

In [77]:
np.exp(a5)

array([[4.85165195e+08, 2.68811714e+43, 5.83461743e+14, 6.56599691e+07,
        2.00855369e+01],
       [2.03828107e+34, 3.26901737e+06, 5.05239363e+31, 1.78482301e+08,
        4.72783947e+18],
       [1.40934908e+22, 1.69488924e+28, 6.39843494e+17, 7.01673591e+20,
        9.25378173e+29],
       [7.49841700e+33, 2.29378316e+27, 1.95729609e+11, 3.02507732e+36,
        1.31881573e+09],
       [3.73324200e+32, 2.83075330e+23, 1.95729609e+11, 3.73324200e+32,
        1.37338298e+32],
       [4.09399696e+35, 1.48413159e+02, 3.58491285e+09, 4.72783947e+18,
        6.56599691e+07]])

In [79]:
np.log10(a5)

array([[1.30103   , 2.        , 1.53147892, 1.25527251, 0.47712125],
       [1.89762709, 1.17609126, 1.86332286, 1.2787536 , 1.63346846],
       [1.70757018, 1.81291336, 1.61278386, 1.68124124, 1.83884909],
       [1.8920946 , 1.79934055, 1.41497335, 1.92427929, 1.32221929],
       [1.87506126, 1.73239376, 1.41497335, 1.87506126, 1.86923172],
       [1.91381385, 0.69897   , 1.34242268, 1.63346846, 1.25527251]])

In [80]:
list(range(0,10, 2))

[0, 2, 4, 6, 8]

In [81]:
np.arange(1.8,10.7,2.5)

array([1.8, 4.3, 6.8, 9.3])

In [82]:
np.linspace(2,3, num=50, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [83]:
np.logspace(2,4, num=4, base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [84]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])